cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2  # 버킷의 리전
    s3:
      bucket: dp-image-save-bucket
    stack:
      auto: false

spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://database-1.cr6cg0ciiz5s.ap-northeast-2.rds.amazonaws.com:5432/dp_DB
    username: postgres
    password: test1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate


  servlet:
    multipart:
      max-file-size: # 업로드할 수 있는 개별 파일의 최대 크기. 기본 1MB
      max-request-size: # multipart/form-data 요청의 최대 허용 크기. 기본 10MB



jwt:
  secret:
    key: ZGVsaXZlcnktcGxhdGZvcm0tcHJvamVjdC1UZWFtIOu5vOu5vOuhnOyhsOyeheuLiOuLpC4=



